"""empty message

Revision ID: 28bf56a67872
Revises: ab3c97e30b5a
Create Date: 2019-07-28 03:03:43.012384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28bf56a67872'
down_revision = 'ab3c97e30b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tomato_category',
    sa.Column('id', sa.CHAR(length=16), nullable=False, comment='唯一id'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='类名'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tomato_tag_relationship',
    sa.Column('id', sa.CHAR(length=16), nullable=False, comment='唯一id'),
    sa.Column('tid', sa.CHAR(length=16), nullable=False, comment='tag id'),
    sa.Column('aid', sa.CHAR(length=16), nullable=False, comment='article id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tomato_article', sa.Column('author', sa.String(length=32), nullable=False, comment='作者'))
    op.add_column('tomato_article', sa.Column('cid', sa.CHAR(length=16), nullable=True, comment='分类id'))
    op.drop_constraint('tomato_article_ibfk_1', 'tomato_article', type_='foreignkey')
    op.drop_column('tomato_article', 'author_id')
    op.add_column('tomato_tag', sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'))
    op.add_column('tomato_tag', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('tomato_tag', sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tomato_tag', 'updated_at')
    op.drop_column('tomato_tag', 'deleted_at')
    op.drop_column('tomato_tag', 'created_at')
    op.add_column('tomato_article', sa.Column('author_id', mysql.CHAR(length=16), nullable=False))
    op.create_foreign_key('tomato_article_ibfk_1', 'tomato_article', 'tomato_user', ['author_id'], ['id'])
    op.drop_column('tomato_article', 'cid')
    op.drop_column('tomato_article', 'author')
    op.drop_table('tomato_tag_relationship')
    op.drop_table('tomato_category')
    # ### end Alembic commands ###
