"""empty message

Revision ID: 8fb3f2e879c1
Revises: 908a9b19e751
Create Date: 2019-09-02 12:03:23.093297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb3f2e879c1'
down_revision = '908a9b19e751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_cid_aid', 'tomato_category_relationship', ['cid', 'aid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_cid_aid', 'tomato_category_relationship', type_='unique')
    # ### end Alembic commands ###
