"""first

Revision ID: ab3c97e30b5a
Revises: 
Create Date: 2019-07-21 09:01:00.349318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3c97e30b5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tomato_menu',
    sa.Column('id', sa.CHAR(length=16), nullable=False, comment='唯一id'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='资源名'),
    sa.Column('url', sa.String(length=128), nullable=False, comment='页面路由'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='菜单排序'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tomato_role',
    sa.Column('id', sa.CHAR(length=16), nullable=False, comment='唯一id'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='角色名称'),
    sa.Column('tag', sa.Integer(), nullable=False, comment='角色类别'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tomato_role_resource',
    sa.Column('id', sa.CHAR(length=16), nullable=False, comment='主键'),
    sa.Column('role_id', sa.CHAR(length=16), nullable=False, comment='角色ID'),
    sa.Column('resource_id', sa.Integer(), nullable=False, comment='资源ID'),
    sa.Column('from_id', sa.Integer(), nullable=False, comment='区别资源类型,1菜单资源'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tomato_tag',
    sa.Column('id', sa.CHAR(length=16), nullable=False, comment='唯一id'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='标签名'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tomato_user',
    sa.Column('id', sa.CHAR(length=16), nullable=False, comment='唯一id'),
    sa.Column('role_id', sa.CHAR(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='用户名称'),
    sa.Column('email', sa.String(length=64), nullable=False, comment='注册邮箱'),
    sa.Column('password', sa.String(length=128), nullable=False, comment='账户密码'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['tomato_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tomato_article',
    sa.Column('id', sa.CHAR(length=16), nullable=False, comment='唯一id'),
    sa.Column('title', sa.String(length=128), nullable=False, comment='标题'),
    sa.Column('author_id', sa.CHAR(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True, comment='文章内容'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['tomato_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tomato_comments',
    sa.Column('id', sa.CHAR(length=16), nullable=False, comment='唯一id'),
    sa.Column('comments', sa.String(length=256), nullable=False, comment='评论'),
    sa.Column('article_id', sa.CHAR(length=16), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['tomato_article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tomato_comments')
    op.drop_table('tomato_article')
    op.drop_table('tomato_user')
    op.drop_table('tomato_tag')
    op.drop_table('tomato_role_resource')
    op.drop_table('tomato_role')
    op.drop_table('tomato_menu')
    # ### end Alembic commands ###
