"""empty message

Revision ID: afe89e5d2a48
Revises: 28bf56a67872
Create Date: 2019-07-28 03:07:24.843785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afe89e5d2a48'
down_revision = '28bf56a67872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tomato_role_relationship',
    sa.Column('id', sa.CHAR(length=16), nullable=False, comment='主键'),
    sa.Column('role_id', sa.CHAR(length=16), nullable=False, comment='角色ID'),
    sa.Column('resource_id', sa.Integer(), nullable=False, comment='资源ID'),
    sa.Column('from_id', sa.Integer(), nullable=False, comment='区别资源类型,1菜单资源'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tomato_role_resource')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tomato_role_resource',
    sa.Column('id', mysql.CHAR(length=16), nullable=False, comment='主键'),
    sa.Column('role_id', mysql.CHAR(length=16), nullable=False, comment='角色ID'),
    sa.Column('resource_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='资源ID'),
    sa.Column('from_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='区别资源类型,1菜单资源'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('tomato_role_relationship')
    # ### end Alembic commands ###
