"""empty message

Revision ID: c366c80f73b4
Revises: 8fb3f2e879c1
Create Date: 2019-09-02 12:18:19.319754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c366c80f73b4'
down_revision = '8fb3f2e879c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tomato_category_relationship', 'id',
               existing_type=mysql.CHAR(length=16),
               comment='主键id',
               existing_comment='唯一id',
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tomato_category_relationship', 'id',
               existing_type=mysql.CHAR(length=16),
               comment='唯一id',
               existing_comment='主键id',
               autoincrement=True)
    # ### end Alembic commands ###
